In [189]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pickle
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from scipy.sparse import hstack
from sklearn.ensemble import RandomForestClassifier

from gensim.models import Word2Vec
import theano.ifelse


In [190]:

train = pickle.load(open('train.p','rb'))
test = pickle.load(open('test.p','rb'))
sentences = train['comment_text']


In [191]:
sent=[]
for item in sentences:
    sent.append(item.split())
print(sent)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


[['messi', 'is', 'better', 'than', 'ronaldo'], ['microsoft', 'is', 'better', 'than', 'yahoo'], ['i', 'am', 'better', 'than', 'you'], ['messi', 'said', 'that', 'i', 'am', 'better', 'than', 'ronaldo']]


In [192]:
model = Word2Vec(iter = 1, size=300, window=6, min_count=0, workers=6, max_vocab_size=None,negative=10)
model.build_vocab(sent)
model.train(sent,total_examples=model.corpus_count,epochs=10,word_count=0,compute_loss=True)
print(model.get_latest_training_loss())


23703820.0


In [193]:
print(model.predict_output_word(['fuck']))
model.most_similar('muslim')

[('vuvuzelas', 0.44712678), ('misterwiki', 0.26793331), ('niggas', 0.11126363), ('off', 0.050557092), ('kike', 0.022720389), ('fuck', 0.020840088), ('cunt', 0.016637523), ('retard', 0.011730277), ('asshole', 0.0070780991), ('motherfucker', 0.0038134861)]


C:\Users\ola.alnaameh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('hindus', 0.7804931402206421),
 ('shia', 0.7546062469482422),
 ('sunni', 0.7144185304641724),
 ('arab', 0.7045628428459167),
 ('islam', 0.7011244297027588),
 ('hindu', 0.652392566204071),
 ('jews', 0.6519992351531982),
 ('islamic', 0.6493295431137085),
 ('kurd', 0.64585280418396),
 ('nonmuslim', 0.6434457302093506)]

In [194]:
tensor = []  
ii=0
for item in sent:
    comm = [model.wv[ii] for ii in item if ii in model.wv.vocab] 
    tensor.append(comm)
    


In [ ]:
print(len(tensor[0]))


In [196]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy import sparse
from keras import layers
from keras.layers import Dense, Embedding, Input,GRU, Flatten, AveragePooling1D,Bidirectional
from keras.layers import Conv2D,Conv1D, MaxPooling1D, GlobalMaxPool1D, Dropout, concatenate

import numpy as np
#train = pickle.load(open('train.p','rb'))
#train=train[0:50000]
#batchSize=500
#featuresN=4000
model = Sequential()
print(model)

model.add(Conv1D(64, 3, activation='relu', padding='same',input_shape=(300, 1)))
model.add(GlobalMaxPool1D())
# model.add(Bidirectional(GRU(60, return_sequences=True,name='lstm_layer',dropout=0.2,recurrent_dropout=0.2)))
# model.add(MaxPooling1D(2))
# model.add(Conv1D(64, 4, activation='relu', padding='causal'))
# model.add(GlobalMaxPool1D())
#model.add(layers.Dense(32,activation='softmax'))
model.add(Dropout(0.5))
#model.add(layers.Dense(32,activation='softmax'))
model.add(Dense(1, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Generate dummy data

#tfidf = TfidfVectorizer(ngram_range=(1,2),max_features=featuresN)
#features = tfidf.fit_transform(train['comment_text'])
#print(features.shape)

#data=tensor
from keras.utils.np_utils import to_categorical
ii = 0
for item in tensor:
#data = tensor#np.expand_dims(item, axis=2)
#X_train_sparse = sparse.csr_matrix(data)

#print(X_train_sparse.shape[0])
    labels=np.array(train['toxic'].tolist())#train[col].tolist()
    #print(len(item))
    #print(np.array(item).shape)
    #print()
    item=np.expand_dims(item, axis=2)
    print(item.shape)
    label=to_categorical(labels[ii])
    label=label.reshape(-1, 1)
    print(label)
#print(np.expand_dims(np.array(data), axis=2).shape)
    model.fit(item, label, epochs=10, batch_size=100)
    ii = ii+1
'''model.fit_generator(generator=batch_generator(X_train_sparse, labels, batchSize, X_train_sparse.shape[0]),
                    nb_epoch=10, 
                    steps_per_epoch=(X_train_sparse.shape[0]/batchSize))
'''

(46, 300, 1)
[[ 1.]]


ValueError: Input arrays should have the same number of samples as target arrays. Found 46 input samples and 1 target samples.

In [158]:
from numpy.random import randint
from numpy import argmax
from keras.utils.np_utils import to_categorical
k = 8
n = 20
x = randint(0, k, (n,))
print(x)
print(to_categorical(x, k))

[2 5 6 4 2 5 5 1 1 5 1 1 5 3 7 4 4 1 4 0]
[[ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]]


In [159]:
len(set(a))

45086

In [84]:
print(comm.shape)
print(item)

(34, 300)
['and', 'i', 'really', 'do', 'not', 'think', '-PRON-', 'understand', 'i', 'come', 'here', 'and', '-PRON-', 'idea', 'be', 'bad', 'right', 'away', 'what', 'kind', 'of', 'community', 'go', '-PRON-', 'have', 'bad', 'idea', 'go', 'away', 'instead', 'of', 'help', 'rewrite', '-PRON-']


In [87]:
[] in sent

True

In [88]:
sent.count([])

7

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy import sparse
from keras import layers
from keras.layers import Dense, Embedding, Input,GRU, Flatten, AveragePooling1D,Bidirectional
from keras.layers import Conv2D,Conv1D, MaxPooling1D, GlobalMaxPool1D, Dropout, concatenate

import numpy as np
#train = pickle.load(open('train.p','rb'))
#train=train[0:50000]
#batchSize=500
#featuresN=4000
model = Sequential()
print(model)

model.add(Conv1D(64, 3, activation='relu', padding='same',input_shape=(None, 1)))
model.add(MaxPooling1D(4))
# model.add(Bidirectional(GRU(60, return_sequences=True,name='lstm_layer',dropout=0.2,recurrent_dropout=0.2)))
# model.add(MaxPooling1D(2))
# model.add(Conv1D(64, 4, activation='relu', padding='causal'))
# model.add(GlobalMaxPool1D())
#model.add(layers.Dense(32,activation='softmax'))
model.add(Dropout(0.5))
#model.add(layers.Dense(32,activation='softmax'))
model.add(Dense(1, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Generate dummy data

#tfidf = TfidfVectorizer(ngram_range=(1,2),max_features=featuresN)
#features = tfidf.fit_transform(train['comment_text'])
#print(features.shape)

#data=tensor
from keras.utils.np_utils import to_categorical
ii = 0
#for item in tensor:
#data = tensor#np.expand_dims(item, axis=2)
#X_train_sparse = sparse.csr_matrix(data)

#print(X_train_sparse.shape[0])
labels=np.array(train['toxic'].tolist())#train[col].tolist()
#print(len(item))
#print(np.array(item).shape)
#print()
item=np.expand_dims(item, axis=2)
print(item.shape)
label=to_categorical(labels[ii])
print(label.shape)
label=label.reshape(-1, 1)
print(label.shape)
#print(np.expand_dims(np.array(data), axis=2).shape)
model.fit(item, label, epochs=10, batch_size=100)
ii = ii+1
'''model.fit_generator(generator=batch_generator(X_train_sparse, labels, batchSize, X_train_sparse.shape[0]),
                nb_epoch=10, 
                steps_per_epoch=(X_train_sparse.shape[0]/batchSize))
'''